# Generated by Django 3.1.5 on 2021-01-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210120_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AddField(
            model_name='user',
            name='gen_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Auto Generated Password'),
        ),
    ]
