# Generated by Django 3.1.5 on 2021-01-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210124_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gen_password',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
