# Generated by Django 3.1.5 on 2021-01-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210124_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
