# Generated by Django 3.1.5 on 2021-01-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
